# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restore dependencies
      run: nuget restore PurrfectBlog\PurrfectBlog.sln
    - name: Build
      run: msbuild PurrfectBlog\PurrfectBlog.sln /p:Configuration=Release
    - name: Test
      run: vstest.console.exe PurrfectBlog.Tests\bin\Release\PurrfectBlog.Tests.dll
